### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by simonrglenn** [learn-co-curriculum/activerecord-validations-readme#11]
"If your validation needs become more complex, consult the documentation."

...needs TO become more complex

**Comment by sgharms** [comment]
Don't think this is a typo.

If your culinary needs become more demanding, buy Shun knives!
If your automotive needs become more demanding, buy a Ferarri!

```text
if
   \ needs____ | become______
      \your      \validation        \complex
                                                \more 
```
