### ISSUE TITLE
record.errors[:name] should be record.errors[:email]

### ISSUE THREAD

**Issue by JustiP3** [learn-co-curriculum/activerecord-validations-readme#13]
At the bottom of the ActiveRecord Validations readme there is an example defining a custom validation. If there is an error in the description it says you should push an error message into record.errors[:attribute] e.g. record.errors[:email] but directly below that there is the text "The result of these steps should be the following:" 
--
     class EmailValidator < ActiveModel::Validator
       def validate(record)
         unless record.email.match?(/flatironschool.com/)
           record.errors[:name] << "We're only allowed to have people who work for the 
     company in the database!"
         end
       end
    end
--
In this example on line 4 it references record.errors[:name] not record.errors[:email]

**Comment by sylwiavargas** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
