### ISSUE TITLE
End of the lesson goes from 0 to 100 real quick

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/activerecord-validations-readme#4]
The [Custom Validators](https://github.com/learn-co-curriculum/activerecord-validations-readme#custom-validators) section is confusingly written. [The linked Rails guide](http://guides.rubyonrails.org/active_record_validations.html#performing-custom-validations) is a much better resource.

**Comment by gb23** [comment]
^What he said a year ago.  Please explain this section better
